GET http://localhost:8080
Content-type: application/json

### Test POST request with JSON body
POST http://localhost:8080
Content-type: application/json

{
  "key": "value"
}



PUT http://localhost:8080
Content-type: application/json

{
  "key": "updatedValue"
}

### Test DELETE request
DELETE http://localhost:8080
Content-type: application/json