CREATE TABLE users (
  ID UUID PRIMARY KEY,
  email VARCHAR(50) NOT NULL,
  user_password VARCHAR(50) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ DEFAULT NOW()
);