CREATE TABLE users (
  ID UUID PRIMARY KEY,
  name_user VARCHAR(50) NOT NULL,
  email VARCHAR(50) NOT NULL,
  password_user VARCHAR(50) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ DEFAULT NOW()
);