CREATE TABLE plants (
    id UUID PRIMARY KEY,
    plant_name VARCHAR(50) NOT NULL,
    plant_description TEXT NOT NULL,
    planting_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    estimated_harvest_date TIMESTAMP NOT NULL,
    plant_status VARCHAR(50) NOT NULL,
    current_height NUMERIC(10, 2) NOT NULL,
    current_width NUMERIC(10, 2) NOT NULL,
    irrigation_week NUMERIC NOT NULL,
    health_status VARCHAR(50) NOT NULL DEFAULT 'Healthy',
    last_irrigation TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_fertilization TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    sun_exposure NUMERIC(10, 2) NOT NULL,
    fertilization_week NUMERIC(10, 2) NOT NULL,
    user_id UUID NOT NULL,
    species_id UUID NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_user_plant FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_species_plant FOREIGN KEY (species_id) REFERENCES species(id) ON DELETE CASCADE
);